# Assessment on Statistics for Decision Making

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy
import sklearn

In [4]:
df = pd.read_csv("F:\Hero Vired - Data Science and Business Analytics Course\Graded Project\Python Project\Statistics for Decision Making\property.csv")
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

#### 1. For the suburb Altona, it is postulated that a typical property sells for 800,000 dollars. Use the data at hand to test this assumption. Is the typical property price really 800,000 dollars or has it increased? Use a significance level of 5%.

In [5]:
from scipy.stats import ttest_1samp


# Filter the dataset for properties in Altona
altona_data = df[df['Suburb'] == 'Altona']

# Extract the prices of the properties
altona_prices = altona_data['Price'].dropna()

# Perform the one-sample t-test
test_result = ttest_1samp(altona_prices, 800000, alternative='greater')

# Extract the test statistic and p-value
test_statistic = test_result.statistic
p_value = test_result.pvalue

# Count the number of properties in Altona
n_properties = len(altona_prices)

print(f"Test Statistic: {test_statistic}")
print(f"P-value: {p_value}")
print(f"Number of Properties: {n_properties}")

# Based on the significance level of 0.05
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: The mean property price in Altona is greater than $800,000.")
else:
    print("Fail to reject the null hypothesis: There is not enough evidence to conclude that the mean property price in Altona is greater than $800,000.")

Test Statistic: 1.0277020770199676
P-value: 0.1537416356527775
Number of Properties: 74
Fail to reject the null hypothesis: There is not enough evidence to conclude that the mean property price in Altona is greater than $800,000.

#### 2. For the year 2016, is there any difference in prices of properties sold in the summer months vs winter months? Consider months from October till March as winter months and rest as summer months. Use a significance level of 5%.

In [6]:
from scipy.stats import ttest_ind

# Convert the Date column to datetime format
df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')

# Filter the dataset for the year 2016
data_2016 = df[df['Date'].dt.year == 2016]

# Define winter and summer months
winter_months = [1, 2, 3, 10, 11, 12]
summer_months = [4, 5, 6, 7, 8, 9]

# Extract property prices for winter and summer months
winter_prices = data_2016[data_2016['Date'].dt.month.isin(winter_months)]['Price'].dropna()
summer_prices = data_2016[data_2016['Date'].dt.month.isin(summer_months)]['Price'].dropna()

# Perform the independent samples t-test
test_statistic, p_value = ttest_ind(winter_prices, summer_prices, equal_var=False)

# Print the results
print(f"Test Statistic: {test_statistic}")
print(f"P-value: {p_value}")

# Based on the significance level of 0.05
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference in mean property prices between summer and winter months.")
else:
    print("Fail to reject the null hypothesis: No significant difference in mean property prices between summer and winter months.")

Test Statistic: 3.9211012778003753
P-value: 8.950129747463378e-05
Reject the null hypothesis: There is a significant difference in mean property prices between summer and winter months.

#### 3. For the suburb of Abbotsford, what is the probability that out of 10 properties sold, 3 will not have car parking? Use the column car in the dataset. Round off your answer to 3 decimal places.

In [7]:
from scipy.stats import binom

# Filter the dataset for the suburb of Abbotsford
abbotsford_data = df[df['Suburb'] == 'Abbotsford']

# Calculate the probability of a property not having car parking in Abbotsford
p_no_parking = 1 - (abbotsford_data['Car'] > 0).mean()

# Number of trials
n = 10

# Number of successes we are interested in
k = 3

# Calculate the probability using the binomial probability formula
probability = binom.pmf(k, n, p_no_parking)

# Round off the answer to 3 decimal places
probability_rounded = round(probability, 3)

# Print the result
print(f"The probability that out of 10 properties sold in Abbotsford, 3 will not have car parking is {probability_rounded}.")

The probability that out of 10 properties sold in Abbotsford, 3 will not have car parking is 0.26.

#### 4. In the suburb Abbotsford, what are the chances of finding a property with 3 rooms? Round your answer to 3 decimal places.

In [8]:
# Filter the dataset for properties in Abbotsford with 3 rooms
abbotsford_3_rooms =df[(df['Suburb'] == 'Abbotsford') & (df['Rooms'] == 3)]

# Calculate the chances of finding a property with 3 rooms in Abbotsford
chances_3_rooms = len(abbotsford_3_rooms) / len(df[df['Suburb'] == 'Abbotsford'])

# Print the chances rounded to 3 decimal places
print(f"Chances of finding a property with 3 rooms in Abbotsford: {chances_3_rooms:.3f}")

Chances of finding a property with 3 rooms in Abbotsford: 0.357

#### 5. In the suburb Abbotsford, what are the chances of finding a property with 2 bathrooms? Round your answer to 3 decimal places.

In [9]:
# Filter the dataset for properties in Abbotsford with 2 bathrooms
abbotsford_data = df[(df['Suburb'] == 'Abbotsford') & (df['Bathroom'] == 2)]

# Calculate the proportion of properties with 2 bathrooms in Abbotsford
chance_2_bathrooms = len(abbotsford_data) / len(df[df['Suburb'] == 'Abbotsford'])

# Print the result rounded to 3 decimal places
print(f"Chances of finding a property with 2 bathrooms in Abbotsford: {chance_2_bathrooms:.3f}")

Chances of finding a property with 2 bathrooms in Abbotsford: 0.339